### ISSUE TITLE
Why didn't you add .sln to the project?

### ISSUE THREAD

**Issue by the-rubicheats** [imhunterand/CS2-Kernel-Driver#2]
I would like to open the project through the .sln file

**Comment by V1ERA** [comment]
even with sln its a virus

**Comment by imhunterand** [comment]
@V1ERA true ;)

**Comment by the-rubicheats** [comment]
> even with sln its a virus

who's good that no one will use it since there's barely a way to compile

**Comment by imhunterand** [comment]
Hi there issue I was marked as `solved` because since asking about `sln` files is a script kiddie question, I hope you can learn about the kernel game project, and understand it. `sln` files are just compiled/after build files, someone who asks for `.sln` files is lazy.
